In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("insurance.csv")
data.head(5)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
data["bmi"]=data["bmi"].astype(int)
data["charges"]=data["charges"].astype(int)

In [4]:
x=data.iloc[:,:-1].values
y=data.iloc[:, -1].values
x

array([[19, 'female', 27, 0, 'yes', 'southwest'],
       [18, 'male', 33, 1, 'no', 'southeast'],
       [28, 'male', 33, 3, 'no', 'southeast'],
       ...,
       [18, 'female', 36, 0, 'no', 'southeast'],
       [21, 'female', 25, 0, 'no', 'southwest'],
       [61, 'female', 29, 0, 'yes', 'northwest']], dtype=object)

In [5]:
y

array([16884,  1725,  4449, ...,  1629,  2007, 29141])

In [6]:
x[:,4]

array(['yes', 'no', 'no', ..., 'no', 'no', 'yes'], dtype=object)

## Encoding

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
x[:,4]=le.fit_transform(x[:,4])


In [8]:
x

array([[19, 0, 27, 0, 1, 'southwest'],
       [18, 1, 33, 1, 0, 'southeast'],
       [28, 1, 33, 3, 0, 'southeast'],
       ...,
       [18, 0, 36, 0, 0, 'southeast'],
       [21, 0, 25, 0, 0, 'southwest'],
       [61, 0, 29, 0, 1, 'northwest']], dtype=object)

In [9]:
np.set_printoptions(threshold=np.sys.maxsize)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
x[:5]

array([[0.0, 0.0, 0.0, 1.0, 19, 0, 27, 0, 1],
       [0.0, 0.0, 1.0, 0.0, 18, 1, 33, 1, 0],
       [0.0, 0.0, 1.0, 0.0, 28, 1, 33, 3, 0],
       [0.0, 1.0, 0.0, 0.0, 33, 1, 22, 0, 0],
       [0.0, 1.0, 0.0, 0.0, 32, 1, 28, 0, 0]], dtype=object)

In [11]:
y=y.reshape(len(y), 1)
y[:5]

array([[16884],
       [ 1725],
       [ 4449],
       [21984],
       [ 3866]])

## Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler

ss_x=StandardScaler()
x=ss_x.fit_transform(x)

ss_y=StandardScaler()
y=ss_y.fit_transform(y)


 ## Training the SVR model on the whole dataset

In [13]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf")
regressor.fit(x,y)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

## Predicting a new result

In [15]:
ss_y.inverse_transform(regressor.predict(ss_x.transform([[0.0, 0.0, 0.0, 1.0, 19, 0, 27, 0, 1]])))

array([22716.83123806])

For the female of 19 years old, ibm = 27, smoker, without children, our model preducts 22716 € charge fee

In [25]:
ss_y.inverse_transform(regressor.predict(ss_x.transform([[0.0, 0.0, 0.0, 1.0, 19, 1, 27, 0, 1]])))

array([21046.97642069])

For the female of 19 years old, ibm = 27, smoker, WITH children, our model preducts 21046 € charge fee

In [27]:
ss_y.inverse_transform(regressor.predict(ss_x.transform([[0.0, 0.0, 0.0, 1.0, 19, 0, 27, 0, 1]])))

array([22716.83123806])